apiVersion: v1
data:
  clusterissuer: "false"
  domain: 34.83.186.205.nip.io
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
